### PR TITLE
Add "saritasa/laravel-middleware" in composer dependencies

### PR DESCRIPTION
**Pull request by veeeeeRySeXy**

### CODE REVIEW

**Comment by populov** [comment]
Why do we need this dependency here? Shouldn't it be in saritasa/laravel-controllers?

**Comment by veeeeeRySeXy** [comment]
In this package uses classed from laravel-middleware package. So i think this dependecy should to be here

**Comment by populov** [comment]
Add new version info with description to CHANGES.md

**Review by populov — CHANGES_REQUESTED** [review]
Add new version info with description to CHANGES.md

**Pull request closed without merging**
